import type { AdminData } from "./types";

/**
 * Seed dataset.
 *
 * This is deliberately a plain, deterministic fixture rather than generated
 * data: the tests assert against it, and a reviewer can read it. Swap this for a
 * database query when one exists — `store.ts` is the only consumer.
 */
export function createSeedData(): AdminData {
  return {
    people: [
      {
        id: "per-001",
        fullName: "Prabhu Balakrishnan",
        email: "prabhu.balakrishnan@certainti.ai",
        department: "Technology",
        jobTitle: "Head of Technology",
        status: "active",
        startDate: "2021-03-01",
      },
      {
        id: "per-002",
        fullName: "Ananya Iyer",
        email: "ananya.iyer@certainti.ai",
        department: "Engineering",
        jobTitle: "Staff Engineer",
        status: "active",
        startDate: "2022-01-17",
      },
      {
        id: "per-003",
        fullName: "Marcus Webb",
        email: "marcus.webb@certainti.ai",
        department: "Engineering",
        jobTitle: "Platform Engineer",
        status: "active",
        startDate: "2023-06-05",
      },
      {
        id: "per-004",
        fullName: "Sofia Marchetti",
        email: "sofia.marchetti@certainti.ai",
        department: "Data Science",
        jobTitle: "ML Engineer",
        status: "active",
        startDate: "2023-09-11",
      },
      {
        id: "per-005",
        fullName: "Rahul Nair",
        email: "rahul.nair@certainti.ai",
        department: "IT Operations",
        jobTitle: "Systems Administrator",
        status: "active",
        startDate: "2022-08-22",
      },
      {
        id: "per-006",
        fullName: "Grace Okafor",
        email: "grace.okafor@certainti.ai",
        department: "Security",
        jobTitle: "Security Analyst",
        status: "active",
        startDate: "2024-02-19",
      },
      {
        id: "per-007",
        fullName: "Daniel Choi",
        email: "daniel.choi@certainti.ai",
        department: "Engineering",
        jobTitle: "Frontend Engineer",
        status: "onboarding",
        startDate: "2026-08-24",
      },
      {
        id: "per-008",
        fullName: "Leena Kapoor",
        email: "leena.kapoor@certainti.ai",
        department: "Finance",
        jobTitle: "Financial Controller",
        status: "active",
        startDate: "2021-11-08",
      },
      {
        id: "per-009",
        fullName: "Tomas Novak",
        email: "tomas.novak@certainti.ai",
        department: "Engineering",
        jobTitle: "Backend Engineer",
        status: "offboarded",
        startDate: "2022-04-04",
      },
      {
        id: "per-010",
        fullName: "Yuki Tanaka",
        email: "yuki.tanaka@certainti.ai",
        department: "Design",
        jobTitle: "Product Designer",
        status: "active",
        startDate: "2024-07-15",
      },
    ],

    assets: [
      {
        id: "ast-001",
        tag: "CTI-LT-0101",
        type: "laptop",
        model: 'MacBook Pro 14" M3',
        serialNumber: "C02X1234JGH7",
        status: "in_use",
        assignedToId: "per-001",
        purchaseDate: "2024-04-12",
        warrantyEndDate: "2027-04-12",
      },
      {
        id: "ast-002",
        tag: "CTI-LT-0102",
        type: "laptop",
        model: 'MacBook Pro 16" M2',
        serialNumber: "C02Y5678KLM2",
        status: "in_use",
        assignedToId: "per-002",
        purchaseDate: "2023-02-20",
        warrantyEndDate: "2026-08-30",
      },
      {
        id: "ast-003",
        tag: "CTI-LT-0103",
        type: "laptop",
        model: "ThinkPad X1 Carbon Gen 11",
        serialNumber: "PF3ZQ8A1",
        status: "in_use",
        assignedToId: "per-003",
        purchaseDate: "2023-07-01",
        warrantyEndDate: "2026-09-05",
      },
      {
        id: "ast-004",
        tag: "CTI-LT-0104",
        type: "laptop",
        model: "Dell XPS 15 9530",
        serialNumber: "5XKQ2M3",
        status: "in_use",
        assignedToId: "per-004",
        purchaseDate: "2023-10-02",
        warrantyEndDate: "2026-10-02",
      },
      {
        id: "ast-005",
        tag: "CTI-LT-0105",
        type: "laptop",
        model: 'MacBook Air 13" M2',
        serialNumber: "C02Z9012NPQ5",
        status: "available",
        assignedToId: null,
        purchaseDate: "2024-01-15",
        warrantyEndDate: "2027-01-15",
      },
      {
        id: "ast-006",
        tag: "CTI-LT-0106",
        type: "laptop",
        model: "ThinkPad T14 Gen 4",
        serialNumber: "PF4AB7C2",
        status: "repair",
        assignedToId: null,
        purchaseDate: "2022-11-30",
        warrantyEndDate: "2025-11-30",
      },
      {
        id: "ast-007",
        tag: "CTI-LT-0107",
        type: "laptop",
        model: "ThinkPad T14 Gen 2",
        serialNumber: "PF1XY9Z3",
        status: "retired",
        assignedToId: null,
        purchaseDate: "2021-05-18",
        warrantyEndDate: "2024-05-18",
      },
      {
        id: "ast-008",
        tag: "CTI-MN-0201",
        type: "monitor",
        model: 'Dell UltraSharp U2723QE 27"',
        serialNumber: "CN0J4T21",
        status: "in_use",
        assignedToId: "per-002",
        purchaseDate: "2023-03-08",
        warrantyEndDate: "2026-03-08",
      },
      {
        id: "ast-009",
        tag: "CTI-MN-0202",
        type: "monitor",
        model: 'LG UltraFine 32" 4K',
        serialNumber: "LG32UN880",
        status: "in_use",
        assignedToId: "per-010",
        purchaseDate: "2024-08-19",
        warrantyEndDate: "2027-08-19",
      },
      {
        id: "ast-010",
        tag: "CTI-MN-0203",
        type: "monitor",
        model: 'Dell UltraSharp U2419H 24"',
        serialNumber: "CN0K8P44",
        status: "available",
        assignedToId: null,
        purchaseDate: "2022-06-14",
        warrantyEndDate: "2025-06-14",
      },
      {
        id: "ast-011",
        tag: "CTI-PH-0301",
        type: "phone",
        model: "iPhone 15",
        serialNumber: "F2LX8N9QRT",
        status: "in_use",
        assignedToId: "per-005",
        purchaseDate: "2024-09-25",
        warrantyEndDate: "2026-09-25",
      },
      {
        id: "ast-012",
        tag: "CTI-PH-0302",
        type: "phone",
        model: "Pixel 8",
        serialNumber: "GP8A2244",
        status: "in_use",
        assignedToId: "per-006",
        purchaseDate: "2024-03-11",
        warrantyEndDate: "2026-08-28",
      },
      {
        id: "ast-013",
        tag: "CTI-SV-0401",
        type: "server",
        model: "Dell PowerEdge R650",
        serialNumber: "SVR7781QW",
        status: "in_use",
        assignedToId: "per-005",
        purchaseDate: "2022-12-01",
        warrantyEndDate: "2026-12-01",
      },
      {
        id: "ast-014",
        tag: "CTI-SV-0402",
        type: "server",
        model: "HPE ProLiant DL380 Gen10",
        serialNumber: "HPE9932ZX",
        status: "in_use",
        assignedToId: "per-005",
        purchaseDate: "2021-09-14",
        warrantyEndDate: "2026-09-14",
      },
      {
        id: "ast-015",
        tag: "CTI-DT-0501",
        type: "desktop",
        model: "Mac Studio M2 Max",
        serialNumber: "C07W4455STD",
        status: "in_use",
        assignedToId: "per-004",
        purchaseDate: "2024-05-30",
        warrantyEndDate: "2027-05-30",
      },
      {
        id: "ast-016",
        tag: "CTI-PR-0601",
        type: "peripheral",
        model: "Logitech MX Master 3S",
        serialNumber: "LG3S7712",
        status: "available",
        assignedToId: null,
        purchaseDate: "2025-01-20",
        warrantyEndDate: "2027-01-20",
      },
      {
        id: "ast-017",
        tag: "CTI-PR-0602",
        type: "peripheral",
        model: "Jabra Evolve2 65 Headset",
        serialNumber: "JB6544AA",
        status: "in_use",
        assignedToId: "per-008",
        purchaseDate: "2023-11-06",
        warrantyEndDate: "2025-11-06",
      },
      {
        id: "ast-018",
        tag: "CTI-LT-0108",
        type: "laptop",
        model: 'MacBook Pro 14" M4',
        serialNumber: "C02A3456UVW8",
        status: "available",
        assignedToId: null,
        purchaseDate: "2026-06-02",
        warrantyEndDate: "2029-06-02",
      },
    ],

    licenses: [
      {
        id: "lic-001",
        vendor: "Atlassian",
        product: "Jira Software (Standard)",
        seatsTotal: 25,
        seatsUsed: 23,
        monthlyCostPerSeatMinor: 79000,
        currency: "INR",
        renewalDate: "2026-09-30",
        ownerId: "per-001",
      },
      {
        id: "lic-002",
        vendor: "Atlassian",
        product: "Confluence (Standard)",
        seatsTotal: 25,
        seatsUsed: 19,
        monthlyCostPerSeatMinor: 55000,
        currency: "INR",
        renewalDate: "2026-09-30",
        ownerId: "per-001",
      },
      {
        id: "lic-003",
        vendor: "GitHub",
        product: "GitHub Enterprise Cloud",
        seatsTotal: 20,
        seatsUsed: 20,
        monthlyCostPerSeatMinor: 178000,
        currency: "INR",
        renewalDate: "2026-08-31",
        ownerId: "per-002",
      },
      {
        id: "lic-004",
        vendor: "Amazon Web Services",
        product: "AWS Support (Business)",
        seatsTotal: 5,
        seatsUsed: 4,
        monthlyCostPerSeatMinor: 830000,
        currency: "INR",
        renewalDate: "2027-01-31",
        ownerId: "per-005",
      },
      {
        id: "lic-005",
        vendor: "Slack",
        product: "Slack Business+",
        seatsTotal: 30,
        seatsUsed: 27,
        monthlyCostPerSeatMinor: 105000,
        currency: "INR",
        renewalDate: "2026-11-15",
        ownerId: "per-001",
      },
      {
        id: "lic-006",
        vendor: "JetBrains",
        product: "All Products Pack",
        seatsTotal: 12,
        seatsUsed: 8,
        monthlyCostPerSeatMinor: 62000,
        currency: "INR",
        renewalDate: "2026-10-05",
        ownerId: "per-003",
      },
      {
        id: "lic-007",
        vendor: "Figma",
        product: "Figma Organization",
        seatsTotal: 8,
        seatsUsed: 5,
        monthlyCostPerSeatMinor: 375000,
        currency: "INR",
        renewalDate: "2026-08-22",
        ownerId: "per-010",
      },
      {
        id: "lic-008",
        vendor: "CrowdStrike",
        product: "Falcon Endpoint Protection",
        seatsTotal: 40,
        seatsUsed: 34,
        monthlyCostPerSeatMinor: 142000,
        currency: "INR",
        renewalDate: "2026-12-31",
        ownerId: "per-006",
      },
      {
        id: "lic-009",
        vendor: "Datadog",
        product: "Datadog Pro (per host)",
        seatsTotal: 15,
        seatsUsed: 15,
        monthlyCostPerSeatMinor: 128000,
        currency: "INR",
        renewalDate: "2026-08-19",
        ownerId: "per-005",
      },
    ],

    accessRequests: [
      {
        id: "req-001",
        requesterId: "per-003",
        system: "Production AWS",
        accessLevel: "admin",
        justification:
          "Need to run the Q3 database migration and roll back if the cutover fails.",
        status: "pending",
        createdAt: "2026-08-14T09:22:00.000Z",
        decidedAt: null,
        decidedById: null,
      },
      {
        id: "req-002",
        requesterId: "per-004",
        system: "Model Training Cluster",
        accessLevel: "write",
        justification:
          "Retraining the churn model on the new feature set; needs write access to the artifact bucket.",
        status: "pending",
        createdAt: "2026-08-15T11:05:00.000Z",
        decidedAt: null,
        decidedById: null,
      },
      {
        id: "req-003",
        requesterId: "per-007",
        system: "GitHub Enterprise",
        accessLevel: "write",
        justification: "New starter — standard engineering repository access.",
        status: "pending",
        createdAt: "2026-08-16T08:40:00.000Z",
        decidedAt: null,
        decidedById: null,
      },
      {
        id: "req-004",
        requesterId: "per-008",
        system: "Billing Console",
        accessLevel: "read",
        justification: "Month-end cloud spend reconciliation.",
        status: "approved",
        createdAt: "2026-08-03T14:12:00.000Z",
        decidedAt: "2026-08-04T09:31:00.000Z",
        decidedById: "per-001",
      },
      {
        id: "req-005",
        requesterId: "per-009",
        system: "Production AWS",
        accessLevel: "admin",
        justification: "Debugging the payment webhook timeouts.",
        status: "denied",
        createdAt: "2026-07-28T16:47:00.000Z",
        decidedAt: "2026-07-29T10:02:00.000Z",
        decidedById: "per-006",
      },
      {
        id: "req-006",
        requesterId: "per-010",
        system: "Figma Organization",
        accessLevel: "admin",
        justification: "Managing the design system library and team permissions.",
        status: "approved",
        createdAt: "2026-08-07T10:15:00.000Z",
        decidedAt: "2026-08-07T15:20:00.000Z",
        decidedById: "per-001",
      },
    ],
  };
}
